FROM node:18-alpine

WORKDIR /app

COPY package*.json pnpm-lock.yaml ./

RUN npm install -g pnpm
RUN pnpm install


COPY . .

RUN pnpm run build

ARG STATE=PROD
ENV STATE=${STATE}

EXPOSE 80

CMD ["sh", "-c", "sleep 300 && node server.js"]
