apiVersion: v1
kind: Pod
metadata:
  name: high-cpu-memory-pod-pending
spec:
  containers:
    - name: cpu-memory-hungry-container
      image: busybox
      command: ["sh", "-c", "while true; do :; done"]
      resources:
        requests:
          cpu: "2000m"
          memory: "1Gi"