apiVersion: v1
kind: Pod
metadata:
  name: main-cronjob
spec:
  containers:
    - name: main-cronjob
      image: busybox
      command: ["sh", "-c", "while true; do :; done"]
      resources:
        requests:
          cpu: "2000m"
          memory: "1Gi"